# Runs one Pod on each eligible Node (or each Node matching the selector/affinity).
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: <app-name>
  namespace: <namespace>
spec:
  selector:
    matchLabels:
      name: <app-name>
  template:
    metadata:
      labels:
        name: <app-name>
    spec:
      containers:
        - name: <container-name>
          image: <image>:<tag>
          volumeMounts:
          - name: <volume-name>
            mountPath: /path
      volumes:
      - name: <volume-name>
        hostPath:
          path: /path
