apiVersion: v1
kind: Secret
metadata:
  name: yelb-db-secret
  namespace: yelb
  labels:
    app.kubernetes.io/name: yelb
    app.kubernetes.io/component: db
    app: yelb
    environment: dev

type: Opaque
stringData:
  database: yelb
  username: yelb
  password: wEAXr$H?HTIi5yrjT!
