---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: podinfo.htdom.lan
  namespace: podinfo

spec:
  dnsNames:
    - podinfo.htdom.lan
  commonName: podinfo.htdom.lan
  secretName: podinfo-pki-secret # server secret
  duration: 2160h                # 90 days
  renewBefore: 360h              # renewal 15 days before expires

  usages:
    - server auth

  privateKey:
    algorithm: ECDSA # or RSA oder ECDSA
    size: 256        # 2048 for RSA/256 for ECDSA
    encoding: PKCS8 
    rotationPolicy: Always

  subject:
    organizations:
      - "HTDOM Inc." # (O) Organization
    organizationalUnits:
      - "Kubernetes" # (OU) Organizational unit
    countries:
      - "DE"         # (C) Country
    localities:
      - "Munich"     # (L) Location

  issuerRef:
    name: htdom-sub-ca
    kind: ClusterIssuer
    group: cert-manager.io
