---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: htdom-root-ca
  namespace: cert-manager

spec:
  commonName: "htdom-root-ca"
  secretName: "htdom-root-ca-secret" # root-ca secret
  isCA: true
  duration: 43830h   # 5 Years
  renewBefore: 720h  # renewal 30 days before expires
  privateKey:
    algorithm: ECDSA # or RSA oder ECDSA
    size: 256        # 2048 for RSA/256 for ECDSA
    encoding: PKCS8 
    rotationPolicy: Never

  usages:
    - digital signature
    - key encipherment
    - cert sign

  subject:
    organizations:
      - "HTDOM Inc." # (O) Organization
    organizationalUnits:
      - "Kubernetes" # (OU) Organizational unit
    countries:
      - "DE"         # (C) Country
    localities:
      - "Muenchen"   # (L) Location

  issuerRef:
    name: htdom-root-ca
    kind: ClusterIssuer
