apiVersion: v1
kind: Service
metadata:
  name: yelb-redis
  namespace: yelb
  labels:
    app.kubernetes.io/name: yelb-redis
    app.kubernetes.io/component: cache
    app: yelb
    environment: dev
    
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app.kubernetes.io/name: yelb-redis
    app.kubernetes.io/component: cache
