apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:/sDn,iv:Zmn3iLXjAbNspXc504VwaNrd4T443oOD5YT5kkkKTN8=,tag:896pe4noLqS3OsnfE6u/ow==,type:str]
    password: ENC[AES256_GCM,data:6a3j6r2+7lce,iv:zovcDYh9+21AGET3HR01jyfwCKuS+YHMbUQ1mFdEZHs=,tag:3RJy8ahv9Iq5ionBJYdu+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV2h3aS8rbVlxVTRqY3J2
            VjkvQmQ4aHIvV0VuVTVURkp6d3pPclJQNDFJCnM0QjVrOGZTdDNFQWYyVmZ5MURn
            VVlpVW53U1VvSHJBck91OHBoMW9wNkEKLS0tIEtDK0ExOWhUL2NyTjhodVlNMUNI
            Z0YwWGFtbkRTWmswRER1eEpsWm5OOGMKW23qMyy1veEBU/22GeQiKpvYEjjdYWl2
            g7gEU3WM4GQdGlTE9Id91h7t03r5efga5/sikCahO1ivRt4X5Mq+Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13kmzf9h8dzqj6casmj9yq5m2jk9hjr2y329tjjv4zr885q87u4uq4uwgv6
    encrypted_regex: ^(data|stringData|password|token|secret|ssh_keys)$
    lastmodified: "2026-05-25T12:36:29Z"
    mac: ENC[AES256_GCM,data:Ec1PoVpAt8o+Q7eqWt9Co0I2KmRbq/H7Yw9r88ah3+0eqwOhnV1hLIpFSswVc7GCOCxkEfV6whKIpcDWFQy9da/cuS3WpZRzZsJjfNZqGIOVElvsPVK3l8laV4NJgydi+1h28us3tTBPq0xiQ3PmE9v6/N+ZTn3Iu9Y5lJBtopw=,iv:SIpRHahBpQNmoArTIXWDWSam+EIDaj5r4742FNmR8TE=,tag:cyzboWsAWJ2+6CHsAk70nQ==,type:str]
    version: 3.13.1
