apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:AgXW,iv:9Z0gNObhX+FOUz6iPZQbyKNBsIClZyQ3ATzTM0mHP30=,tag:RWJanQr1mP6AIgeYVRzvmg==,type:str]
    password: ENC[AES256_GCM,data:ZBMo5O3y6l6S,iv:lPKkMF1ztlaRc0mOgobXM2JJDqvSxxL2jWBZ14juD+Q=,tag:9YodIveD44TL6ZQU8JxItw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQVMzTThxcUJMNzMyRjNa
            aFFNd2lCbzZyY1c5ZW9mOTIwOEFxMStyZ0NNCkNWRFNFZzFYUGRvVWdQWjdKV2xH
            L3JsL0hFYXpJOXRnNjBpRk5Ha0pXc3cKLS0tIG5qSkE4TXFjRGhzb0kwRWJYOXFa
            YXk0eitRU0laTXQyNEVENUhhbEVzcnMKQNJd7h40BpOQaJlFJD0AZsYTo4rUUrCF
            C6vrB+gPWjKx1EywS4oGDz+WiKHrrXgoz8iwTlygu/0TtY5aqnKQ2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13kmzf9h8dzqj6casmj9yq5m2jk9hjr2y329tjjv4zr885q87u4uq4uwgv6
    encrypted_regex: ^(data|stringData|password|token|secret|ssh_keys)$
    lastmodified: "2026-05-24T18:52:05Z"
    mac: ENC[AES256_GCM,data:tU7vxNi3hqxRqK4fR2UzN1fuTOt6mIqk5b71HK85jVY7wJkjca+dqPHoMjzXrOoQt9RSATTuTh4so6eI7cBhLZ0kAr34D3nxJmuGfuLETjbiS+ncFeJifWH+J8GpvM4NS6NJr0YKp/6xv4MypSsnB4c9R7gASaYp6thhhxu3S54=,iv:ltL8JgjButcAAiiLXBxTq70/3dIIiMLEY07/tFVPk0A=,tag:y0Ar6Lk6a2bA4VtrCvbn9w==,type:str]
    version: 3.13.1
