apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-secret
    namespace: postgresql
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:uS0C2wF7eg==,iv:0u4EX8lZrbpsOew+9IDpvBAfN0+NKPWmxWD9eAe5SMU=,tag:i4n/C/4OYuBNoGLkdiYazQ==,type:str]
    password: ENC[AES256_GCM,data:ZHM+YB58tcLj530=,iv:YETAVzRSf10tmdPn8PeXH/hfW56ZUG0HwrKLlokuHhM=,tag:v72T6qLt8qqrGT45MCO35Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSHo4OFlDMUVFS3I4NUF4
            OUNQNFU4VWgvNXZaUzI2S1QxQURlRndqZlJZCncvcTg2VXF1THBpdG5IMGZ4eFZI
            YTdleUZqYXViMEFtTmxSWGxJZUdtZmcKLS0tIGhQSExuZjhTWDJ6QlZzZGp2d0dO
            d25FNmNtOXlwSGZjOXhzYk9DOE9NcEkKURUupeVlrBe7ES5A/ol6rdtUfhMrGf8v
            KzdqSwb9HU63z9QFuEllMntN+ulZZ4WiuTXQVjBiRunbluV8N6Z5NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13kmzf9h8dzqj6casmj9yq5m2jk9hjr2y329tjjv4zr885q87u4uq4uwgv6
    encrypted_regex: ^(data|stringData|password|PASSWD|token|secret|ssh_keys)$
    lastmodified: "2026-05-25T15:53:07Z"
    mac: ENC[AES256_GCM,data:ZicvtU5USe4WWqG2AJS1dyBkr8NFziBGkmzOrcSPnfzPQeGKMbnsuu/ngDejyXefWkhaq+F0b8FoNKv/yWXnKN3I7Z33mQXZn/wHPM3zu9KuDiMZPKQn+56CyaHPbSrl4tXZZ6UhNA4K+xUBv5oJYr37lMBiV4mEe/5zYG4HlPw=,iv:2sZDHEEFNf2jOJNhBRhoZzTaw7Cg6DiZJwo6hQnj7L4=,tag:wN817rF7chkW7UsfAOfGpQ==,type:str]
    version: 3.13.1
