apiVersion: v1
kind: Secret
metadata:
    name: yelb-db-secret
    namespace: yelb
    labels:
        app.kubernetes.io/name: yelb
        app.kubernetes.io/component: db
        app: yelb
        environment: dev
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:/Z6rdQ==,iv:ebzNy75aSBKeOQBOIcvxXE8Kfy6Lv8415YFgxE18kMM=,tag:W79y0dInUK7tnoAF9Z4OGA==,type:str]
    username: ENC[AES256_GCM,data:vCh3RA==,iv:XAKJR+d5+cnrakL9uInVWLJvONjf7lsiymyOl6aqDe0=,tag:XynGh/GBZ2IGSN+MsrjTpA==,type:str]
    password: ENC[AES256_GCM,data:awht6hSfCLJvaapFI9HNG/jp,iv:S31WTVnlOqkxDdf86v7/ROvbbcfnGjJsB85Eee3saZ0=,tag:NnoQE8qjgTQH8wrW5g850A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RWhJNEdDNWExK2RQWVV6
            aHBENCtHM2JuZ0xZSWprVXNMcTQ2UWxnQXlNCkZrMDZ6dkEvZVpSZzlQMlQ2dFJo
            SFdkNlNWaWQ1RWhxZ0xCMmFRRnVZQlUKLS0tIGN1dVFNZmNZeVJLZXl4THpLR3R5
            ZjlrMGtqZ1FUcVFURFFFRDlJUHJUTm8KQVswxhkO3TJzvN84dwZaIUh6q355pSpz
            8F0LahL1jiT3agDQmQ1TFJEqpqkNrd+x30kdXZHzE4BLUVg+NlRxWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13kmzf9h8dzqj6casmj9yq5m2jk9hjr2y329tjjv4zr885q87u4uq4uwgv6
    encrypted_regex: ^(data|stringData|password|PASSWD|token|secret|ssh_keys)$
    lastmodified: "2026-10-08T15:41:56Z"
    mac: ENC[AES256_GCM,data:lQpuYln32u76Eb9uWbKnHb+hELkVTvLBM0mVhVEbBaHgokKsxDOVAdsvDmyBJBFKDqP8yViekzUzgDMWl+4jbnw7VKaoY5i4FsZiP2ljIF8gMeLx3t9l8rDaYwSvZVnXoNtFW32KUdaElvSe0d67IMu/p+Uada4jpfFFV6J2tj8=,iv:Ktybjt4zSm0B+KzcQpDXhTpvuIBM0kcKr7miR0qVdr0=,tag:8Kh9JXvW5+yqM7L7Fe+KZg==,type:str]
    version: 3.13.3
