apiVersion: v1
kind: Secret
metadata:
    name: yelb-db-secret
    namespace: yelb
    labels:
        app.kubernetes.io/name: yelb
        app.kubernetes.io/component: db
        app: yelb
        environment: dev
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:4LsW/djmuC9Mra8S,iv:Lu8Q5eS8FjxRg+whKyZr8coacnLSwUsUcG27whUCUo4=,tag:DWBd+W/jlnBZu/pct0N0PA==,type:str]
    username: ENC[AES256_GCM,data:E3V1h6lIr2I=,iv:w0SMKEi9p+SJ6jNB05CILbVHILmyjKq56mPMBnVUuW8=,tag:uKUaA58wWeBhg86rwVyUJQ==,type:str]
    password: ENC[AES256_GCM,data:7BKBLak5427oSpavNrcySEc=,iv:rDAKp/Ayj5mYLgbGQHpQRQArnHLMqicpdc4yKk2/ZsE=,tag:wFznK8vkVRf597FkPSFZPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWUhCNmNUcFB0b0RMNEhJ
            aEpZYkxMeUYra3BnTzdKR2VLYTZCMjlCUlhjClNEK3JMWVFJQitYVVo4QjlSMXFE
            MDdkSnpFZFdwZzFmMk96UGlleHJDemsKLS0tIHVzWi9XL2JHV2I2VGw1RS9vcGtt
            cHZXTmgwTHNkSjloVWs5aVp0UUVyaUkKzutriVqAl59T5b0+Si1xoMcx5fu4yEgt
            Q8BtDBQfYVq4tjl/bZNdZsD47n0weeqpJu6uSuWLO4i8pYZkQVY1sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13kmzf9h8dzqj6casmj9yq5m2jk9hjr2y329tjjv4zr885q87u4uq4uwgv6
    encrypted_regex: ^(data|stringData|password|PASSWD|token|secret|ssh_keys)$
    lastmodified: "2026-10-09T10:45:17Z"
    mac: ENC[AES256_GCM,data:8ZErFUoTdtP9gtELQrJBeo9Hi3SzikJsEFZIspJkhfMfUPIvuggaM8ixmdyXPRT3XJ6eRpmvEZy9Jhu28Vt55u5//p3nIUJCCmocg0tsIMJicYOHN+dw7xJZ0jikMLubq+UgYjQwanOOvyMOU70eXYW5uq6X0fok6idDUT++X9c=,iv:zQ0jLoqhtspDDa5uQEWWOSHUNQpWA3+ISLTWeayl3+I=,tag:MR+wXGH+aZP6Kkx6ATiIuw==,type:str]
    version: 3.13.3
